=== azltdanh/tool-validate-content-ingestion/exchange-v-1-0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'
           elementFormDefault='qualified'
           targetNamespace="http://www.elesevier.com/eols/recommendation/remediation/exchange/v1.0"
           xmlns="http://www.elesevier.com/eols/recommendation/remediation/exchange/v1.0">
    <xs:import namespace='http://www.w3.org/XML/1998/namespace' schemaLocation='https://www.w3.org/2001/xml.xsd'/>
    <xs:element name='rec-remediation-data'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name='created-ts' type='xs:dateTime'/>
                <xs:element ref='question-banks' minOccurs='0'/>
                <xs:element ref='page-domains' minOccurs='0' />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='questions'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='question' minOccurs='0' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='question'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name='topics-verified-ts' type='xs:dateTime' minOccurs='0'/>
                <xs:element ref='topics' minOccurs='0'/>
            </xs:sequence>
            <xs:attribute name='id' use='required' type='xs:string'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='topics'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='topic' minOccurs='0' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='topic'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name='group' type='GroupLabel'/>
                <xs:element name='name' type='xs:string'/>
                <xs:element name='hgraph-id' type='HGraphID' minOccurs='0'/>
                <xs:element name='weight' type='xs:double' minOccurs='0'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='question-banks'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='question-bank' minOccurs='0' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='question-bank'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name='name' type='xs:string'/>
                <xs:element name='description' type='xs:string'/>
                <xs:element ref='questions' minOccurs='0'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='pages'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='page' minOccurs='0' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='page'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="resource" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name='topics-verified-ts' type='xs:dateTime' minOccurs='0'/>
                <xs:element ref='topics' minOccurs='0'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='page-domains'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='page-domain' minOccurs='0' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='page-domain'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name='name' type='xs:string'/>
                <xs:element name='url-template' type='xs:string'/>
                <xs:element name='description' type='xs:string'/>
                <xs:element ref='pages' minOccurs='0'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="GroupLabel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Anatomy"/>
            <xs:enumeration value="Clinical Finding"/>
            <xs:enumeration value="Disease"/>
            <xs:enumeration value="Drug"/>
            <xs:enumeration value="Event"/>
            <xs:enumeration value="Organism"/>
            <xs:enumeration value="Other"/>
            <xs:enumeration value="Physical Object"/>
            <xs:enumeration value="Procedure"/>
            <xs:enumeration value="Specialty"/>
            <xs:enumeration value="Substance"/>
            <xs:enumeration value="Symptom"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="HGraphID">
        <xs:restriction base="xs:string">
            <xs:pattern value="id-.+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== azltdanh/tool-validate-content-ingestion/exchange-v-1-0.xml
<?xml version="1.0" encoding="UTF-8"?>
<rec-remediation-data xmlns="http://www.elesevier.com/eols/recommendation/remediation/exchange/v1.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://www.elesevier.com/eols/recommendation/remediation/exchange/v1.0 exchange-v-1-0.xsd">
    <created-ts>2018-11-13T12:13:56Z</created-ts>
    <question-banks>
        <question-bank>
            <name>UK_Clinical_Medicine</name>
            <description>this has questions</description>
            <questions>
                <question id="YAI_199">
                    <topics-verified-ts>2018-11-13T12:13:56Z</topics-verified-ts>
                    <topics>
                        <topic>
                            <group>Anatomy</group>
                            <name>Gastrointestinal tract</name>
                            <hgraph-id>id-170428c1-45fb-3e32-bc66-779455faedba</hgraph-id>
                        </topic>
                    </topics>
                </question>
            </questions>
        </question-bank>
    </question-banks>
    <page-domains>
        <page-domain>
            <name>images</name>
            <url-template>www.cloudfronturl.com/</url-template>
            <description>this is hosted in s3</description>
            <pages>
                <page>
                    <resource>vaccines</resource>
                    <description>this is about flu vaccines</description>
                    <topics>
                        <topic>
                            <group>Disease</group>
                            <name>influenza</name>
                        </topic>
                    </topics>
                </page>
            </pages>
        </page-domain>
    </page-domains>
</rec-remediation-data>

=== azltdanh/tool-validate-content-ingestion/sampleBank_question-topic_topic-page_mappings_V1.xml
<?xml version='1.0' encoding='UTF-8'?>
<rec-remediation-data xmlns="http://www.elesevier.com/eols/recommendation/remediation/exchange/v1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.elesevier.com/eols/recommendation/remediation/exchange/v1.0 exchange-v-1-0.xsd">
	<created-ts>2019-01-30T08:30:32Z</created-ts>
	<question-banks>
		<question-bank>
			<name>MedEd_Sample_Bank</name>
			<description>MedEd Sample Bank</description>
			<questions>
				<question id="YAI_10001000">
					<topics>
						<topic>
							<group>Disease</group>
							<name>whooping cough</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
				<question id="YAI_10001001">
					<topics>
						<topic>
							<group>Disease</group>
							<name>meningitis</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
				<question id="YAI_10001002">
					<topics>
						<topic>
							<group>Disease</group>
							<name>Lyme disease</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
				<question id="YAI_10001003">
					<topics>
						<topic>
							<group>Disease</group>
							<name>influenza</name>
							<weight>0.8</weight>
						</topic>
						<topic>
							<group>flu vaccination</group>
							<name>flu vaccination</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
				<question id="YAI_10001004">
					<topics>
						<topic>
							<group>Disease</group>
							<name>asthma</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
				<question id="YAI_10001005">
					<topics>
						<topic>
							<group>Disease</group>
							<name>ear infection</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
			</questions>
		</question-bank>
	</question-banks>
	<page-domains>
		<page-domain>
			<name>TOPIC</name>
			<url-template>https://ck2-cert.clinicalkey.com/meded</url-template>
			<description>TOPIC Example</description>
			<pages>
				<page>
					<resource>/meded/api/topic/pertussis</resource>
					<topics>
						<topic>
							<group>Disease</group>
							<name>whooping cough</name>
						</topic>
					</topics>
				</page>
				<page>
					<resource>/meded/api/topic/meningitis</resource>
					<topics>
						<topic>
							<group>Disease</group>
							<name>meningitis</name>
						</topic>
					</topics>
				</page>
				<page>
					<resource>/meded/api/topic/Lyme disease</resource>
					<topics>
						<topic>
							<group>Disease</group>
							<name>Lyme disease</name>
						</topic>
					</topics>
				</page>
				<page>
					<resource>/meded/api/topic/asthma</resource>
					<topics>
						<topic>
							<group>Disease</group>
							<name>asthma</name>
						</topic>
					</topics>
				</page>
				<page>
					<resource>/meded/api/topic/influenza</resource>
					<topics>
						<topic>
							<group>Disease</group>
							<name>influenza</name>
						</topic>
					</topics>
				</page>
			</pages>
		</page-domain>
		<page-domain>
			<name>IMAGE</name>
			<url-template>https://content-qa.els-ols.com/1085XTLVQR0/image/</url-template>
			<description>IMAGE Example</description>
			<pages>
				<page>
					<resource>earInfection.jpg</resource>
					<topics>
						<topic>
							<group>Disease</group>
							<name>ear infection</name>
						</topic>
					</topics>
				</page>
				<page>
					<resource>fluVaccination.jpg</resource>
					<topics>
						<topic>
							<group>flu vaccination</group>
							<name>flu vaccination</name>
						</topic>
					</topics>
				</page>
			</pages>
		</page-domain>
	</page-domains>
</rec-remediation-data>

=== azltdanh/tool-validate-content-ingestion/backup/sampleBank_question-topic_topic-page_mappings_V3.xml
<?xml version="1.0" encoding="UTF-8"?>
<rec-remediation-data xmlns="http://www.elesevier.com/eols/recommendation/remediation/exchange/v1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.elesevier.com/eols/recommendation/remediation/exchange/v1.0 exchange-v-1-0.xsd">
	<created-ts>2019-01-30T08:30:32Z</created-ts>
	<question-banks>
		<question-bank>
			<name>MedEd_Sample_Bank</name>
			<description>MedEd Sample Bank</description>
			<questions>
				<question id="YAI_10001000">
					<topics>
						<topic>
							<group>Disease</group>
							<name>Whooping Cough</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
				<question id="YAI_10001001">
					<topics>
						<topic>
							<group>Disease</group>
							<name>Meningitis</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
				<question id="YAI_10001002">
					<topics>
						<topic>
							<group>Disease</group>
							<name>Lyme Disease</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
				<question id="YAI_10001003">
					<topics>
						<topic>
							<group>Disease</group>
							<name>Influenza</name>
							<weight>0.8</weight>
						</topic>
						<topic>
							<group>Flu Vaccination</group>
							<name>Flu Vaccination</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
				<question id="YAI_10001004">
					<topics>
						<topic>
							<group>Disease</group>
							<name>Asthma</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
				<question id="YAI_10001005">
					<topics>
						<topic>
							<group>Disease</group>
							<name>Ear Infection</name>
							<weight>0.8</weight>
						</topic>
					</topics>
				</question>
			</questions>
		</question-bank>
	</question-banks>
	<page-domains>
		<page-domain>
			<name>TOPIC</name>
			<url-template>https://ck2-cert.clinicalkey.com/meded</url-template>
			<description>TOPIC Example</description>
			<pages>
				<page>
					<resource>/meded/api/topic/Pertussis</resource>
					<description />
					<topics>
						<topic>
							<group>Disease</group>
							<name>Whooping Cough</name>
						</topic>
					</topics>
				</page>
				<page>
					<resource>/meded/api/topic/Meningitis</resource>
					<description />
					<topics>
						<topic>
							<group>Disease</group>
							<name>Meningitis</name>
						</topic>
					</topics>
				</page>
				<page>
					<resource>/meded/api/topic/Lyme Disease</resource>
					<description />
					<topics>
						<topic>
							<group>Disease</group>
							<name>Lyme Disease</name>
						</topic>
					</topics>
				</page>
				<page>
					<resource>/meded/api/topic/Asthma</resource>
					<description />
					<topics>
						<topic>
							<group>Disease</group>
							<name>Asthma</name>
						</topic>
					</topics>
				</page>
				<page>
					<resource>/meded/api/topic/Influenza</resource>
					<description />
					<topics>
						<topic>
							<group>Disease</group>
							<name>Influenza</name>
						</topic>
					</topics>
				</page>
			</pages>
		</page-domain>
		<page-domain>
			<name>IMAGE</name>
			<url-template>https://content-qa.els-ols.com/1085XTLVQR0/image/</url-template>
			<description>IMAGE Example</description>
			<pages>
				<page>
					<resource>earInfection.jpg</resource>
					<description />
					<topics>
						<topic>
							<group>Disease</group>
							<name>Ear Infection</name>
						</topic>
					</topics>
				</page>
				<page>
					<resource>fluVaccination.jpg</resource>
					<description />
					<topics>
						<topic>
							<group>Flu Vaccination</group>
							<name>Flu Vaccination</name>
						</topic>
					</topics>
				</page>
			</pages>
		</page-domain>
	</page-domains>
</rec-remediation-data>
